import type { Metadata } from "next";
import LearnLayout from "@/components/learn/LearnLayout";
import SectionShell from "@/components/site/SectionShell";
import { getLearnRoute } from "@/data/learnRoutes";

const route = getLearnRoute("interpretation")!;

export const metadata: Metadata = {
  title: route.title,
  description: route.summary,
};

export default function InterpretationPage() {
  return (
    <LearnLayout route={route}>

      <SectionShell label="Interpretation is not explanation">
        <p className="text-nt-body leading-relaxed mb-4">
          Explanation tells you what the system did. Interpretation tells you
          what the system{"\u2019"}s output means for what can happen next. These
          are structurally different activities. Confusing them is the source of
          most deployment governance failures.
        </p>
        <p className="text-nt-body leading-relaxed">
          An explanation can be generated by the same system that produced the
          output. Interpretation requires a reader with a model of the surface
          that the output inhabits{" "}
          <span className="text-nt-dim">
            {"\u2014"} a model the system does not have of itself.
          </span>
        </p>
      </SectionShell>

      <SectionShell label="Five readings">
        <div className="space-y-5">
          {[
            {
              label: "Residue",
              description:
                "What prior decisions are still active in the current surface? Residue is the constraint inherited from earlier commitments. Reading residue correctly prevents the system from appearing to offer options it cannot actually deliver.",
            },
            {
              label: "Optionality",
              description:
                "Which paths remain genuinely open from this point? Not which paths the system offers{sep}which paths remain recoverable if the next commitment goes wrong.",
            },
            {
              label: "Instability signature",
              description:
                "Where is the surface most sensitive to small input changes? Instability signatures mark the zones where the system is most likely to produce outputs that diverge from the intended commitment boundary.",
            },
            {
              label: "Topology temperature",
              description:
                "How much is the surface moving relative to baseline? High temperature is not bad{sep}it is a condition requiring different operating discipline. Low temperature is not safe{sep}it may indicate the surface has gone rigid.",
            },
            {
              label: "Admissibility posture",
              description:
                "What is the current relationship between this system\u2019s outputs and the admissibility conditions required for commitment? Posture is not a score. It is a reading of direction and distance.",
            },
          ].map(({ label, description }) => (
            <div key={label} className="border border-nt-border rounded p-5">
              <p className="text-nt-heading text-sm font-medium mb-2">{label}</p>
              <p className="text-nt-dim text-sm leading-relaxed">
                {description.replace(/\{sep\}/g, "\u2014")}
              </p>
            </div>
          ))}
        </div>
      </SectionShell>

      <SectionShell label="The governed explanation interface">
        <p className="text-nt-body leading-relaxed mb-4">
          A governed explanation interface constrains what the system is allowed
          to present as its rationale. Ungoverned, a system will offer the most
          locally coherent explanation available{" "}
          <span className="text-nt-dim">
            {"\u2014"} which is often the explanation that sounds best, not the
            one that maps to the actual decision structure.
          </span>
        </p>
        <p className="text-nt-body leading-relaxed">
          Governing the interface means defining the boundaries of what counts
          as an admissible explanation for a given output type. It is a design
          constraint, not a post-hoc label.
        </p>
      </SectionShell>

      <SectionShell label="Governing principle">
        <blockquote className="border-l-2 border-nt-accentDim pl-4">
          <p className="text-nt-body text-sm leading-relaxed italic">
            The system can tell you what it did. Only a practitioner with a
            model of the surface can tell you what it means for what comes next.
            Interpretation is not a system output. It is a practitioner
            obligation.
          </p>
        </blockquote>
      </SectionShell>

    </LearnLayout>
  );
}
